### ISSUE TITLE
Wrong encoding in taglib

### ISSUE THREAD

**Issue by Rapster** [primefaces/maven-jsf-plugin#2]
More details here https://forum.primefaces.org/viewtopic.php?f=3&t=46540&p=158801#p158801

It's hard to explain why it's happening... But at least with this modification, UTF-8 is used for sure ;-)

**Comment by Rapster** [comment]
@tandraschko Since you know about this problem (see forum), you might merge the associated PR

**Comment by Rapster** [comment]
Do you think it is possible to make a release of this? I fork PF in my company but I don't wanna have to fork maven-jsf-plugin too

**Comment by tandraschko** [comment]
it's up to @mertsincan or @cagataycivici  - never did any release ;)

**Comment by Rapster** [comment]
Okay we'll see what they have to say about that then. I think, PF pom.xml should depend on maven-jsf-plugin release version and not on a snapshot version. Developer have to clone the repository as well to make PF work, which is not convinient.
