### ISSUE TITLE
No longer use ComponentMojo to generate classes

### ISSUE THREAD

**Issue by Rapster** [primefaces/maven-jsf-plugin#4]
I'm just suggesting this idea, but generating component through the template is no longer a good idea (I don't think it ever was...) 

But when it comes to make modifications on the component, it is so much pain, specially when it comes to make simple add or modifications... You have to regenerate your source code, of course you might change your build path but that's called fiddling... Plus When you're about to commit change, there is a risk you might forget something from your template... I can do a PR for this

**Comment by tandraschko** [comment]
probably the best way is do write something like RichFaces CDK or somthing similar to lombok - but i'm really not sure as the effort is quite high.

**Comment by Rapster** [comment]
Don't know about the Richfaces CDK, I thought about lombok but, I don't think it's  good idea. From hat I saw, depending the JDK you might have problem. I like the simple way like PFE does (e.g manually :D, no automating) Of course, I'm only talking about the component generation, nothing else

**Comment by Rapster** [comment]
I'm still thinking about the lombok thing... Let's skip what I just said for a moment :D

The annotation would generate:

- COMPONENT_TYPE, COMPONENT_FAMILY, DEFAULT_RENDERER static attributes
- Getter/Setter for the corresponding PropertyKeys
- resolveWidgetVar function if component implementing `Widget` interface

See http://notatube.blogspot.fr/2010/12/project-lombok-creating-custom.html

**Comment by Rapster** [comment]
Given that the state of  Primefaces is really mature and not meant to have "big" changes in the future. I think we should stick to manual changes (much more simple than current doing or above proposals). I added a link for annotations processing though since I think it's interesting approach

**Comment by Rapster** [comment]
I have started to work on this ticket, I realize PF depends on this plugin for no good reason (everything could be simply contained in PF module) I think we should get rid of maven-jsf-plugin... What do you think?

**Comment by tandraschko** [comment]
-1 currently as it's quite time consuming and it's time for a release in ~1-2 months.

there are also some other reasons:
- i have to discuss this with the team
- manual getter/setters are a no go (for me personally)
- we still need the plugin for other features

Also i don

**Comment by Rapster** [comment]
> there are also some other reasons:
> 
> - i have to discuss this with the team
> - manual getter/setters are a no go (for me personally)

What's wrong with that?
> - we still need the plugin for other features

Which ones? I had a look we don't use TagMojo, TLDMojo and TimestampMojo. We use three that we can easily do without

**Comment by tandraschko** [comment]
Do you mean whats wrong with manuel getter/setter? Almost everything :D takes to much LOC, also errors can easily happen by copy&paste.

The one which generates the taglib and faces-config. the taglib is very big and it doesn't make fun to maintain it manually.

**Comment by Rapster** [comment]
Don't understand your point regarding the lines of code (LOC)? Regarding copy & paste, I don't see where you're going with this... I created a unit test that check the definition of the components (based on what maven-jsf-plugin used to generated) It's simple and wrks nicely ;-) I do understand your point with the xml files though, but use a plugin just for that, that's heavy... and I don't think it's difficult to maintain (specially with IDE we have today)..

**Comment by tandraschko** [comment]
This doesn't easier as the current plugin ;)
i would only change that whole mechanism if the result is perfect or almost perfect. The manual solution is just a little bit better for me.

**Comment by Rapster** [comment]
Let's talk about the template files instead, it's far from being easy, it cost so much during development! You were talking about copy& paste, well... sometimes you have those, but you don't realize you forgot some imports, you don't realize it does not build for obvious reasons, so you have to generate sources all over again... (Let's be honest it's a waste of time) I'm sure I miss some obvious points ;-) Even though you still want to keep the plugin, ComponentMojo should be removed, a unit test would do the job so much better (I even found inconsistency in the java definition of some component with it :D )

**Comment by tandraschko** [comment]
Yep, templates are definitely not nice. It's hard to maintain.

But as i said, getter/setter are not nice.
For me something like this would be perfect:

`public class MyComponent {  
   @SomeAnnotation(description="..", default="...", required=false)   
   public String getMyAttribute();  
}
`
OR

`public class MyComponent {  
   enum Attributes {  
       @SomeAnnotation(description="..", default="...", required=false, type=String.class)  
       myAttirbute;  
   }  
}  `

i don't think it's to hard with lombok. And AFAIK it's not necessary to deviler lombok as dependency as the lombok plugin would compile it.

**Comment by Rapster** [comment]
If I follow your arguments, I wouldn't write getter/ setter at all. And an annotation like `@PFComponent` should be enough. I'll have a look using lombok

**Comment by tandraschko** [comment]
exactly.

We also have 2 possible ways then:
- just have a attribute annotation with the attribute type and defaultValue
      and reuse the old plugin and maintain descriptions via xml
- maintain also the description in the annotation
     and write a new plugin to generate the taglib based on those annotations

**Comment by Rapster** [comment]
Using Lombok, that's what I would have in mind
```java
@ResourceDependencies({
	@ResourceDependency(library="primefaces", name="signature/signature.css"),
	@ResourceDependency(library="primefaces", name="jquery/jquery.js"),
	@ResourceDependency(library="primefaces", name="jquery/jquery-plugins.js"),
	@ResourceDependency(library="primefaces", name="core.js"),
	@ResourceDependency(library="primefaces", name="components.js"),
	@ResourceDependency(library="primefaces", name="signature/signature.js")
})
@PFComponent(description = "Signature is an input component to provide a signature",
             componentType = "org.primefaces.component.Signature",
             componentFamily = "org.primefaces.component",
             rendererType = "org.primefaces.component.SignatureRenderer")
public class Signature extends UIInput implements org.primefaces.component.api.Widget {

	public enum PropertyKeys {
	    @PFProperty(description = "Name of the client side widget")
		widgetVar,
		@PFProperty(defaultValue = "#ffffff", description = "Background color, default is #ffffff")
		backgroundColor,
		@PFProperty(defaultValue = "#000000", description = "Foreground color, default is #000000")
		color,
		@PFProperty(defaultValue = "2", description = "Thickness of lines, default is 2")
		thickness,
		@PFProperty(description = "Inline style of the component")
		style,
	    @PFProperty(description = "Style class of the component")
		styleClass,
		@PFProperty(type = Boolean.class, description = "When enabled, signature is used for display purposes only")
		readonly,
		@PFProperty(description = "Adds a guideline when enabled, default is false")
		guideline,
		@PFProperty(defaultValue = "#a0a0a0", description =  "Color of the guideline, default is #a0a0a0")
		guidelineColor,
		@PFProperty(defaultValue = "25", type = Integer.class, description = "Offset of guideline from bottom")
		guidelineOffset,
		@PFProperty(defaultValue = "10", type = Integer.class, description ="Guide line indent from the edges")
		guidelineIndent,
		@PFProperty(description = "Client side callback to execute when signature changes")
		onchange,
		@PFProperty(description = "Write-only value used to pass the value in base64 to backing bean")
		base64Value;

		String toString;

		PropertyKeys(String toString) {
			this.toString = toString;
		}

		PropertyKeys() {}

		public String toString() {
			return ((this.toString != null) ? this.toString : super.toString());
}
	}

    public void processUpdates(FacesContext context) {
        super.processUpdates(context);
        String base64Value = getBase64Value();

        if(base64Value != null) {
            ValueExpression ve = this.getValueExpression(PropertyKeys.base64Value.toString());
            if(ve != null) {
                ve.setValue(context.getELContext(), base64Value);
                getStateHelper().put(PropertyKeys.base64Value, null);
            }
        }
    }
}
```

COMPONENT_TYPE, COMPONENT_FAMILY, DEFAULT_RENDERER, Getter/Setter
resolveWidgetVar should be handled by Lombok processor. Let's keep in mind Lombok hack the compiler. 

There is another approach that could be done by using Google Auto approach, and I think we wouldn't need any third party library to do so. We define a component (SignatureCore) as usual, an interface would generated containing getters/setters based on PropertyKeys, the processor generates a subclass (Signature) and implements everything:

```java
@ResourceDependencies({
	@ResourceDependency(library="primefaces", name="signature/signature.css"),
	@ResourceDependency(library="primefaces", name="jquery/jquery.js"),
	@ResourceDependency(library="primefaces", name="jquery/jquery-plugins.js"),
	@ResourceDependency(library="primefaces", name="core.js"),
	@ResourceDependency(library="primefaces", name="components.js"),
	@ResourceDependency(library="primefaces", name="signature/signature.js")
})
@PFComponent(description = "Signature is an input component to provide a signature",
             widget = true,
             rtl = true)
public abstract class SignatureCore extends UIInput implements ISignature {
        
    public enum PropertyKeys {
	    @PFProperty(description = "Name of the client side widget")
		widgetVar,
		@PFProperty(defaultValue = "#ffffff", description = "Background color, default is #ffffff")
		backgroundColor,
		@PFProperty(defaultValue = "#000000", description = "Foreground color, default is #000000")
		color,
		@PFProperty(defaultValue = "2", description = "Thickness of lines, default is 2")
		thickness,
		@PFProperty(description = "Inline style of the component")
		style,
	    @PFProperty(description = "Style class of the component")
		styleClass,
		@PFProperty(type = Boolean.class, description = "When enabled, signature is used for display purposes only")
		readonly,
		@PFProperty(description = "Adds a guideline when enabled, default is false")
		guideline,
		@PFProperty(defaultValue = "#a0a0a0", description =  "Color of the guideline, default is #a0a0a0")
		guidelineColor,
		@PFProperty(defaultValue = "25", type = Integer.class, description = "Offset of guideline from bottom")
		guidelineOffset,
		@PFProperty(defaultValue = "10", type = Integer.class, description ="Guide line indent from the edges")
		guidelineIndent,
		@PFProperty(description = "Client side callback to execute when signature changes")
		onchange,
		@PFProperty(description = "Write-only value used to pass the value in base64 to backing bean")
		base64Value;

		String toString;

		PropertyKeys(String toString) {
			this.toString = toString;
		}

		PropertyKeys() {}

		public String toString() {
			return ((this.toString != null) ? this.toString : super.toString());
}
	}

    public void processUpdates(FacesContext context) {
        super.processUpdates(context);
        String base64Value = getBase64Value();

        if(base64Value != null) {
            ValueExpression ve = this.getValueExpression(PropertyKeys.base64Value.toString());
            if(ve != null) {
                ve.setValue(context.getELContext(), base64Value);
                getStateHelper().put(PropertyKeys.base64Value, null);
            }
        }
    }
}
```

ISignature would be generated and containing all the getters/setters.

**Comment by tandraschko** [comment]
1) looks nicer
2) looks very similar to RichFaces CDK

**Comment by Rapster** [comment]
1. Looks more difficult to implement https://stackoverflow.com/a/41318338/4605161
2. Looks way more easier

**Comment by Rapster** [comment]
So far, I'd go with solution 2/ I changed few things and looks very nice but... I'm struggling with inheritance,... Let's take WidgetVar for instance. The idea is to avoid to declare once again PropertyKeys.widgetvar but how to do that? 

- Is it that important SIgnatureCore.PropertyKeys contains widgetVar attributes, just wondering? Otherwise, developers can simply use WidgetVar.PropertyKeys

**Comment by tandraschko** [comment]
Sent a mail to Cagatay - Currently +1 from my side for manually setter/getter generation, as it's the simplest way with less effort.
We have some many issues in the issuetracker, i think we should such "candy"-tickets later.

**Comment by Rapster** [comment]
Sure, I started to work on something (with code generation, see one of my last post), will push something in the coming days ;-)

**Comment by Rapster** [comment]
https://github.com/Rapster/primefaces-cdk is the annotation processor used to generate classes
https://github.com/Rapster/primefaces/tree/fix-primefaces-with-cdk is a fork of primefaces using the annotation processor

**Comment by tandraschko** [comment]
Cool stuff! (and much effort of course!)

AFAICS it's just for the component class generation? What about the taglibs? I think we should avoid 2 plugins/dependencies.

Just some notes:
- Whats IAccordionPanel? 
- Don't like the naming till now:
  - AccordionPanelCore - i think AbstractAccordionPanel would fit it better, alternative would be: AccordionPanelBase
  - All annotations are called PF* - What about using something like CdkProperty as it isn't bound directly to PF. Also it's not a PFProperty, it would be a PfComponentProperty.
- PFComponent has rtl and widget attribute. Woudln't be better to use use @Component + @Widget instead?

**Comment by Rapster** [comment]
1. So far, it only covers class generation, I plan to work on the taglibs generation as well. FYI we could use FacesComponent annotation to register component... Are you sure PF client are still using JSF 2.1?
2. I'm open to any proposal regarding the naming ;-) IAccordionPanel is an interface containing getters/setters (needed in case AccordianPanelCore makes call of these)
3. I want to minimize the use of annotation, so I like PFComponent having attributes instead of new annotations

**Comment by tandraschko** [comment]
1) yep. we should still support JavaEE6.
2) Is it generated on the fly? Why we can't generate it into the abstract class? Currently we have 1 class finally, with your changes we have 3. the abstract class, a interface and a class. Feels to much.
3) I see but we do we still have PFWidget then?

**Comment by Rapster** [comment]
1. Okay
2. It can be generated on the fly, Eclipse has the option for doing so but I didn't try yet. I do agree on the fact 3 classes can be a lot, I can have a look for generating only one, but I'll give you a simple example why I'm not up for it 100%, the code in the `AbstractAccordionPanel` will look like this:
```java
    @Override
    public void setStyle(String style) {
        getStateHelper().put(AccordionPanel.PropertyKeys.style, style);
    }
```
Doing so in the parent class looks strange don't you think? Making reference to a child class from the parent...
3. PFWidget is used to find/identify the interface definining a widget

**Comment by tandraschko** [comment]
2) hmmm... I thought that the IDE will check that, that the getter/setter are automatically generated and it will compile. Like with lombok.
Otherwise it would be ok if the code looks like this and the setter/getter will be implemented in the real class:

`public abstract class AbstractAccordionPanel {
    class PropertyKeys {
      style...
    }

   public abstract String getStyle();
   public abstract void setStyle(String style);
}
`

3) But you already have PFComponent(widget=true)?

**Comment by Rapster** [comment]
2. as I said, Eclipse can generate the code during a build process https://marketplace.eclipse.org/content/m2e-apt. Lombok hack the compiler, which IMO is not a good idea. The idea of processor is to avoid the creation of getters/setters, this is the first thing you said no? Otherwise, it's pointless to use primefaces-cdk...

3.  `PFComponent(widget=true)` only indicates it's a widget, but to identify what is the interface to implement, I'm using `PFWidget`. This is probably temporary, since I was thinking passing an argument to the processor to identify the interfaces (such as Widget, RTLAware, etc.)

**Comment by tandraschko** [comment]
2. Yep sure, but it's better to place them inside the abstract class and don't implement them instead of creating interfaces. Also noone of the PF team uses Eclipse.

**Comment by Rapster** [comment]
I'm quite sure every IDE use annotation processing tool. So what I'll do is, generate an abstract class containing all the getters/setters, will implement Widget and RTLAware if necessary and the constants will be there as well

**Comment by tandraschko** [comment]
I'm not sure if i can follow but i have no time to check it in detail for now.

I must really say, i don't like those interfaces Isn't there a way to get rid of them?
Also we must really get sure that it works fine in NetBeans+IntelliJ and in a normal maven build without IDE.


I also don't understand the benefit of rtl/widget and the annotations.
Why can't we just have this:
abstract class AbstractAccordionPanel extends UIComponentBase implements Widget, RTLAware ?

Adding additional attributes or Annotations feels to much.

**Comment by Rapster** [comment]
I realized sometimes we use camel case naming or lowercase naming for tag name. Which one should we prefer?

**Comment by tandraschko** [comment]
camel case ;)

**Comment by Rapster** [comment]
Why aren't we using `@FacesConverter` `@FacesValidator` `@FacesComponent` to register component? It's available in JEE 6. This way we wouldn't have to handle the registration through faces-config.xml

**Comment by tandraschko** [comment]
There were containers in the past which had problems to scan it correctly. I also was pinged some months ago that it still doesn't work for 100%.

**Comment by Rapster** [comment]
Mmm strange... sounds more like a JSF impl than a container problem, but okay

**Comment by tandraschko** [comment]
It depends how much the JSF impl is integrated in the container ;) 
e.g. TomEE scans one time all classes before initializing JAX-RS, JSF, ... , ... - therefore it's so fast.

**Comment by Rapster** [comment]
Thomas, regarding what Arjan said, what do you think we should do? Waiting for the new approach like Arjan mentionned or create our own generator. IMO, if CDI is required, I'm not thrilled about this idea, as you mentionned, performance, but also, companies are not all using CDI (mine does not 😄). I like the idea to not using big tool to do simple things, after all, what we need at the end is to generate getters and setters.

**Comment by tandraschko** [comment]
"waiting" doesn't change anything for us, we have to be compatible with older and newer versions.

I probably also don't see any big benefit of using CDI in the component tree.
Also a generator is not really necessary for us, the current approach is ok. We can even go the way to manually add getter/setters as PF is major and it's unlikely that we will develop many many new components in a year.

**Comment by Rapster** [comment]
Ah ok so maybe I should let go `primefaces-cdk` then _(but I really liked the idea of the code being documented-self)_. So we agree on manually add the getters and setters, I think it would be a lot better than what PF has today. To ensure the correctness of these, a simple unit test can be executed, as simple as that :wink:

**Comment by Rapster** [comment]
I was reading the whole discussion from the start, I understand your point of view, when it comes to:

1. Having 3 classes for one component is too much. But I had no choice, the parent class/interface had to be generated because from the component (e.g AccordionBase) you may call getters or setters. 

**UPDATE: I think this is the "best" doable approach**

2. The PFWidget and PFRTL are used identify the interfaces, I'm fully aware it's strange and looks complicated. If I had to work on that again, I would get rid of this and simply pass these as a parameter to the annotation processor

At the end, I'd have something like this:
![image](https://user-images.githubusercontent.com/7521311/38516459-7cd4135c-3c37-11e8-87e8-f71a1a94782e.png)

**UPDATE: Java 8 won't help 100%. The idea to generate component constructor setting the renderer is won't be possible either only generating interfaces, like this:**

```java
	public AccordionPanel() {
		setRendererType(DEFAULT_RENDERER);
	}
```


I had in mind to use default method _(but it requires to upgrade java version of PF)_ in order to generate everything in the interface (like this you only need one thing generated!) In the picture, PropertyKeys is still a nested class.

**Comment by tandraschko** [comment]
We can't upgrade to java8 currently.
And we should check if it maybe possible without getter/setter.

**Comment by Rapster** [comment]
Yeah yeah I know, I'm not saying we should to do that right now. What do you mean without getters/setters?

**Comment by tandraschko** [comment]
If the values are available via the statehelper, also if there is no setter defined for the property.

**Comment by Rapster** [comment]
So instead of calling `getBackground()`, we'd have to call `getStateHelper().eval(PropertyKeys.background, "gray");`?

**Comment by tandraschko** [comment]
getStateHelper isn't public but something like that yes. But the default value should be evaluated internal.

**Comment by Rapster** [comment]
You clearly have a better understanding/knowledge of the API than I do, so I'm not sure what you have in mind. But what about users using binding just like this: 

```xml
<p:signature background="gray" binding="#{sign}" />
<h:outputText value="#{sign.background}" />
```

If we use something else than getters, how could this be achieved?

**Comment by tandraschko** [comment]
Sorry but don't understand the relation to your example.

The question is: does the facelet-compiler really use the setter in the component class to put the value in or is the logic hidden in the statehelper? So maybe removing the setter from the component class doesn't change anything.
I don't know this part very good ;)

**Comment by Rapster** [comment]
> "waiting" doesn't change anything for us, we have to be compatible with older and newer versions.

> I probably also don't see any big benefit of using CDI in the component tree.
> Also a generator is not really necessary for us, the current approach is ok. We can even go the way to manually add getter/setters as PF is major and it's unlikely that we will develop many many new components in a year.

@tandraschko @melloware What about doing this for PF 6.3 then?

**Comment by melloware** [comment]
i personally would like it.  Someone mentioned to me the way RichFaces did it with annotations was worth looking at as well.

**Comment by tandraschko** [comment]
my last question isn't answered yet.

i really would like to keep complexity low, so i wouldn't introduce a new "framework" for components.
PF is stable and we don't change attributes that much, so i think the manual way is ok.

**Comment by Rapster** [comment]
Of course Thomas, I was talking about doing the manual way. Regarding your question, I guess we can have a quick try by debugging. For a first step, I would keep it simple and just copy and paste the generated class where it belongs. We can figure something out after that.

**Comment by tandraschko** [comment]
ok, then +0.5 :D

We should still check how we implement it. Maybe splitting up properties and everything else makes sense in multiple classes:

e.g.
javax.*.UIComponentBase
javax.*.UIInput
pf.*.InputTextBase (abstract class with all properties)
pf.*.InputText (component class with additional methods like queueEvent...)

We should just think about if the Base or the Component class has the @ResourceDependencies and "extends/implements"

**Comment by Rapster** [comment]
Not sure I follow you. I would keep it simple by copying and pasting the generated classes. (the idea being to get rid of `maven-jsf-plugin`)

**Comment by Rapster** [comment]
We should do this before new charts and calendar are about to be developed or after integration into PF (but not during). @mertsincan Do you know when the development pocess will start?

**Comment by Rapster** [comment]
> We should just think about if the Base or the Component class has the @ResourceDependencies and "extends/implements"

I think `@ResourceDependencies` should be set to the component implementation extending the XXXBase (since the base should only contains the boilerplate)
